# Generated by Django 4.1.4 on 2022-12-29 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="post", name="body",),
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(default="Hasibul Islam", max_length=264),
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("ব্যক্তিগত", "ব্যক্তিগত"),
                    ("ব্লগ", "ব্লগ"),
                    ("ধর্মীয়", "ধর্মীয়"),
                    ("ফিকশন", "ফিকশন"),
                    ("অন্যান্য", "অন্যান্য"),
                ],
                default="ব্যক্তিগত",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="post",
            name="img1",
            field=models.ImageField(blank=True, upload_to="static/uploads"),
        ),
        migrations.AddField(
            model_name="post",
            name="img10",
            field=models.ImageField(blank=True, upload_to="static/uploads"),
        ),
        migrations.AddField(
            model_name="post",
            name="img10caption",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="post",
            name="img1caption",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="post",
            name="img2",
            field=models.ImageField(blank=True, upload_to="static/uploads"),
        ),
        migrations.AddField(
            model_name="post",
            name="img2caption",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="post",
            name="img3",
            field=models.ImageField(blank=True, upload_to="static/uploads"),
        ),
        migrations.AddField(
            model_name="post",
            name="img3caption",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="post",
            name="img4",
            field=models.ImageField(blank=True, upload_to="static/uploads"),
        ),
        migrations.AddField(
            model_name="post",
            name="img4caption",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="post",
            name="img5",
            field=models.ImageField(blank=True, upload_to="static/uploads"),
        ),
        migrations.AddField(
            model_name="post",
            name="img5caption",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="post",
            name="img6",
            field=models.ImageField(blank=True, upload_to="static/uploads"),
        ),
        migrations.AddField(
            model_name="post",
            name="img6caption",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="post",
            name="img7",
            field=models.ImageField(blank=True, upload_to="static/uploads"),
        ),
        migrations.AddField(
            model_name="post",
            name="img7caption",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="post",
            name="img8",
            field=models.ImageField(blank=True, upload_to="static/uploads"),
        ),
        migrations.AddField(
            model_name="post",
            name="img8caption",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="post",
            name="img9",
            field=models.ImageField(blank=True, upload_to="static/uploads"),
        ),
        migrations.AddField(
            model_name="post",
            name="img9caption",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="post", name="para1", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para10", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para100", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para11", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para12", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para13", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para14", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para15", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para16", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para17", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para18", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para19", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para2", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para20", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para21", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para22", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para23", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para24", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para25", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para26", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para27", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para28", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para29", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para3", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para30", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para31", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para32", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para33", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para34", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para35", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para36", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para37", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para38", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para39", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para4", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para40", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para41", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para42", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para43", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para44", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para45", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para46", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para47", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para48", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para49", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para5", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para50", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para51", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para52", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para53", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para54", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para55", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para56", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para57", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para58", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para59", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para6", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para60", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para61", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para62", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para63", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para64", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para65", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para66", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para67", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para68", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para69", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para7", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para70", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para71", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para72", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para73", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para74", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para75", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para76", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para77", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para78", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para79", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para8", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para80", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para81", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para82", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para83", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para84", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para85", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para86", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para87", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para88", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para89", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para9", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para90", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para91", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para92", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para93", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para94", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para95", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para96", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para97", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para98", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post", name="para99", field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="post", max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
